export const demos = [
    { title: 'Hierarchy' },
    { title: 'Events' },
    { title: 'Loader' },
    { title: 'Gltf' },
    { title: 'Liquid Box', url: '/demo/liquid-box/' },
    { title: 'Basic' },
    { title: 'Shadows' },
    { title: 'Custom Shader', url: '/demo/custom-shader/' },
    { title: 'Custom Scene', url: '/demo/custom-scene/' },
    { title: 'Camera Switch', url: '/demo/camera-switch/' },
    { title: 'Custom Render', url: '/demo/custom-render/' },
    { title: 'Orthographic Camera', url: '/demo/ortho-camera/' },
    { title: 'Before/After Render', url: '/demo/before-after-render/' },
]
