import { h, defineComponent } from 'vue'
import { LunchboxWrapper } from './LunchboxWrapper/LunchboxWrapper'
import { autoGeneratedComponents } from './autoGeneratedComponents'

import { catalogue } from './catalogue'
export { catalogue }

export const lunchboxDomComponentNames = ['canvas', 'div', 'LunchboxWrapper']

// component creation utility
const createComponent = (tag: string) =>
    defineComponent({
        inheritAttrs: false,
        name: tag,
        setup(props, context) {
            return () => h(tag, context.attrs, context.slots?.default?.() || [])
        },
    })

autoGeneratedComponents.map(createComponent).reduce((acc, curr) => {
    ;(acc as any)[curr.name] = curr
    return acc
})

export const components = {
    ...autoGeneratedComponents,
    Lunchbox: LunchboxWrapper,
}
